source 'https://rubygems.org'
ruby '2.3.1'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-flash'
gem 'rake'
gem 'rest-client', '~> 1.8'
gem 'pry', '~> 0.10.4'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'nokogiri'
